version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "[INSTALL] Nothing to install"

  pre_build:
    commands:
      - echo "=== DEBUG: Where am I? ==="
      - pwd
      - echo "=== DEBUG: What files are here? ==="
      - ls -la
      - echo "[PRE_BUILD] Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 084828587056.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=084828587056.dkr.ecr.us-east-1.amazonaws.com/blockchain-voting-repo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo "[BUILD] Build started on $(date)"
      - echo "[BUILD] Checking contents again before building..."
      - ls -la
      - echo "[BUILD] Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest -f Dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "[POST_BUILD] Build completed on $(date)"
      - echo "[POST_BUILD] Pushing Docker images to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "[POST_BUILD] Writing imagedefinitions.json..."
      - printf '[{"name":"blockchain-voting-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
    - scripts/*  # Include if CodeDeploy hooks use scripts
